import React from 'react'
import BreadCamp from '../components/BreadCamp'
import { API_URL } from '../stor'

export default function RefundPolicy() {
    return (
        <div>
            {/* <BreadCamp img={API_URL+"other-images/IMG_4954.JPG"} name={"Refund & Cancellation policy"} /> */}
            <h4 className='text-2xl  lg:mx-24 text-white font-bold text-center border-t-8 border-secondary py-3 bg-primary'>Refund & Cancellation policy</h4>

            <section className='lg:px-24 pb-14 p-4'>
               
                <h3 className='text-lg px-5 font-bold text-white bg-primary border-t-4 border-secondary py-3 mt-5'>1. Non-Refundable Registration Fees</h3>
                <p className='my-3 px-5'>
                The fees paid towards registration is non-refundable and non-transferable under any circumstances unless the trial is officially cancelled by the organizers.

                </p>
                <h3 className='text-lg px-5 font-bold text-white bg-primary border-t-4 border-secondary py-3 mt-5'>2. Refund in Case of Cancellation:</h3>
                <p className='my-3 px-5'>
                If, due to unforeseen circumstances or natural calamities, the trial is Cancelled, the registration amount will be refunded after deducting GST and 20% of service charges of the registration fee. <br />
The refund process will be initiated within 30 working days from the day of cancellation of selection trials and the balance amount after deducting GST and 20% service charges will be credited to your account within 10-15  business days after processing.

                </p>
                <h3 className='text-lg px-5 font-bold text-white bg-primary border-t-4 border-secondary py-3 mt-5'>3. Refund Process & Mode</h3>
                <p className='my-3 px-5'>
                Refunds will be processed to the original payment method used during registration. <br />
The participant must provide accurate banking details (if required) for successful processing.

                </p>
                <h3 className='text-lg px-5 font-bold text-white bg-primary border-t-4 border-secondary py-3 mt-5'>4. Important Disclaimer</h3>
                <p className='my-3 px-5'>
                <b>Please note:</b> The registration fee is solely for the trials and has no connection with the league. <br />
If, after the trials, the league is Cancelled due to any reason, MacJhons is not liable to pay anything to anyone, as the registration fee covers only the trials and not the league participation.

                </p>
                <h3 className='text-lg px-5 font-bold text-white bg-primary border-t-4 border-secondary py-3 mt-5'>5. Organizer's Rights:</h3>
                <p className='my-3 px-5'>
                MJPL reserves the right to make decisions regarding refunds and cancellations. <br />
Any disputes related to refunds will be addressed on a case-by-case basis, and the decision of the organizers shall be final and binding.
</p>
<p className='px-5'><b>6. Organizers</b> will not be held responsible in case of delay of payment due to technical glitches and or otherwise server issue of the recipient bank.</p>
<br />
<p className='px-5'><b>7. Refund</b> will be done in serial number generated by our system as per your registration on our portal and refund will be processed accordingly.
</p>
                <h3 className='text-lg px-5 font-bold text-white bg-primary border-t-4 border-secondary py-3 mt-5'>8. Contact Information</h3>
                <p className='my-3 px-5'>
                    If you have any questions or concerns about this Privacy Policy, please contact us at: <br /> <br />
                    Email - <b> info@macjhons.com</b> <br />
                    Phone -  <b> +91 7021612227</b> <br />
                    Address - <b>B-3, Sai Ashiyana, Nr Aziziya Masjid, Mira Road (E), Mira Road, Mira Bhayander, Thane, Thane- 401107, Maharashtra, India
                    </b>

                </p>
            </section>
        </div>
    )
}
